[project]
name = "hackrx"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "fastapi",
    "graphiti-core[google-genai]>=0.3.21",
    "pydantic-ai>=0.4.7",
]
